In [7]:
import pandas as pd

raw_data = pd.DataFrame({
        'bioguideId': ['A1', 'B2', 'C3'],
        'name': ['Erik', 'Edgar', 'Erik'],
        'surname': ['Ruiz', 'Mendez', 'Mendozini'],
        'partyName': ['Democratic', 'Republican', 'Democratic'],  # Uno se tiene que ir
        'state': ['CA', 'TX', 'NY']  # Uno está en minúsculas
    })

In [8]:
raw_data.head()

  bioguideId   name    surname   partyName state
0         A1   Erik       Ruiz  Democratic    CA
1         B2  Edgar     Mendez  Republican    TX
2         C3   Erik  Mendozini  Democratic    NY

In [12]:
silver_df = raw_data.copy()

silver_df = silver_df[silver_df['partyName'] == 'Democratic']   

silver_df['state'] = silver_df['state'].str.lower()

silver_df.head()

  bioguideId  name    surname   partyName state
0         A1  Erik       Ruiz  Democratic    ca
2         C3  Erik  Mendozini  Democratic    ny